### PR TITLE
Update UsefulPrefixes.cs

### PR DESCRIPTION
**Pull request by erxson**

### CODE REVIEW

**Comment by erxson** [comment]
@Qiu233

**Comment by erxson** [comment]
Best prefixes from Wiki
Best for melee + exclusion
Best for ranged + exclusion
Best for magic/summon + exclusion
Best for accessories

**Comment by erxson** [comment]
I missed my pull request's birthday ;(

**Comment by Qiu233** [comment]
sorry, I have nearly forgotten this.

**Comment by erxson** [comment]
this was the longest april fools prank of all time
image

**Pull request merged**
