### PR TITLE
Update UsefulPrefixes.cs

### PR DESCRIPTION
**Pull request by erxson**

### CODE REVIEW

**Review by erxson — COMMENTED** [review]
фыв

**Comment by erxson** [comment]
@Qiu233

**Comment by erxson** [comment]
best prefixes

**Comment by Qiu233** [comment]
I'm sorry, this pr will be checked later.

**Comment by erxson** [comment]
the best pr in the world

**Comment by erxson** [comment]
Accept if you're not dead yet

**Comment by erxson** [comment]
@Qiu233

**Pull request closed without merging**
